#!/bin/bash
# Version: v.22.05.30

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="${SCRIPT_PATH}"
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"
cd "${ODOO_WORK_DIR}"

if [ "$(id -u)" -eq 0 ]; then
  /bin/echo "Please dont use sudo command with script"
  exit 1
fi

#rm -fr ./auto/odoo.conf
#rm -fr ./auto/addons/*
#/bin/bash -c "$(/bin/ls -1 ./custom/src | grep -Ev 'private|repos.yaml|addons.yaml' | /usr/bin/awk '{print("rm -fr ./custom/src/" $1)}')"

if [ ! -d "${ODOO_WORK_DIR}/.venv" ]; then
    /bin/echo 'run ./bootstrap first!'
    exit 1
fi

# pip 20.3 has a neat depenency resolver
# https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020
. "${ODOO_WORK_DIR}/.venv/bin/activate" && \
"${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet "setuptools-scm<8.0" && \
if [[ "$(/bin/echo "${ODOO_VERSION}" | /usr/bin/cut -d '.' -f1)" -ge 15 ]]; then
  if [[ "$(/bin/echo "${ODOO_VERSION}" | /usr/bin/cut -d '.' -f1)" -le 17 ]]; then
    "${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet "setuptools>=64,<82"
  else
    "${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet setuptools
  fi
else
  if [[ "$(/bin/echo "${ODOO_VERSION}" | /usr/bin/cut -d '.' -f1)" -eq 11 ]]; then
    "${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet "setuptools<58"
  else
    "${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet "setuptools<82"
  fi
fi && \
"${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet "pip>=20.3" && \
("${ODOO_WORK_DIR}/.venv/bin/python" -m pip uninstall --yes -r "${ODOO_WORK_DIR}/requirements-remove-default.txt" 2>/dev/null || /bin/true) && \
"${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet --exists-action w -r "${ODOO_WORK_DIR}/requirements-default.txt" && \
"${ODOO_WORK_DIR}/.venv/bin/python" -m pip install --quiet --exists-action w -r "${ODOO_WORK_DIR}/requirements.txt" && \
"${ODOO_WORK_DIR}/common/build" && \
"${ODOO_WORK_DIR}/.venv/bin/python" "${ODOO_WORK_DIR}/common/entrypoint"
