#!/bin/bash
# Version: v.22.05.30

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="${SCRIPT_PATH}"
. "${ODOO_WORK_DIR}/.env-default" && \
. "${ODOO_WORK_DIR}/.env-shared" && \
. "${ODOO_WORK_DIR}/.env-secret"
export ODOO_I18N_OVERWRITE="${ODOO_I18N_OVERWRITE:-false}"

if [ "${#}" -eq 0 ]; then
  /bin/echo "Upgrade a module"
  /bin/echo "Usage: ./upgrade-module modulename"
  exit
fi

cd "${ODOO_WORK_DIR}" && \
 . "${ODOO_WORK_DIR}/.venv/bin/activate" && \

if [[ "$(/bin/echo ${ODOO_VERSION} | /usr/bin/cut -d '.' -f1)" -lt 19 ]]; then
  export ODOO_SHELL_PORT="xmlrpc-port"
else
  export ODOO_SHELL_PORT="http-port"
fi

if [[ "${ODOO_I18N_OVERWRITE,,}" != 'true' ]] ; then
  "${ODOO_WORK_DIR}/.venv/bin/odoo" -c ./auto/odoo.conf -u "${1}" --"${ODOO_SHELL_PORT}"=18069 --stop-after-init
else
  "${ODOO_WORK_DIR}/.venv/bin/odoo" -c ./auto/odoo.conf -u "${1}" --"${ODOO_SHELL_PORT}"=18069 --stop-after-init --i18n-overwrite
fi
